[package]
name = "mamoru-sniffer-go"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[profile.release]
opt-level = "z"
strip = true
lto = true

[dependencies]
mamoru-sniffer-c = {git = "https://github.com/Mamoru-Foundation/mamoru-core", rev = "6273683041ad08c9155dfe83cf3a4ce37d87846e"}
#mamoru-sniffer-c = {path = "../mamoru-core/mamoru-sniffer-c"}
