[package]
name = "mamoru-sniffer-go"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[profile.release]
opt-level = "z"
strip = true
lto = true

[dependencies]
mamoru-sniffer-c = {git = "https://github.com/Mamoru-Foundation/mamoru-core", rev = "8349f355c9dac5431333fcba1d4b8a1f80f07267"}
#mamoru-sniffer-c = {path = "../mamoru-core/mamoru-sniffer-c"}
