[package]
name = "mamoru-sniffer-go"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[profile.release]
opt-level = "z"
strip = true
lto = true

[dependencies]
mamoru-sniffer-c = {git = "https://github.com/Mamoru-Foundation/mamoru-core", rev = "0839078ec5b84e682beed292426c0b0a7f017fbb"}
#mamoru-sniffer-c = {path = "../mamoru-core/mamoru-sniffer-c"}
