[package]
name = "mamoru-sniffer-go"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[profile.release]
opt-level = "z"
strip = true
lto = true

[dependencies]
mamoru-sniffer-c = {git = "https://github.com/Mamoru-Foundation/mamoru-core", rev = "13ae3903607438698306f4235f1023a54ee1b5a3"}
#mamoru-sniffer-c = {path = "../mamoru-core/mamoru-sniffer-c"}
