[package]
name = "mamoru-sniffer-go"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[profile.release]
opt-level = "z"
strip = true
lto = true

[dependencies]
#mamoru-sniffer-c = {git = "https://github.com/Mamoru-Foundation/mamoru-core", rev = "0bbe1d74d14c9d50cc7dd6ce5de3b5b5587f362e"}
mamoru-sniffer-c = {path = "../mamoru-core/mamoru-sniffer-c"}
