[package]
name = "mamoru-sniffer-go"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[profile.release]
opt-level = "z"
strip = true
lto = true

[dependencies]
#mamoru-sniffer-c = {path = "../mamoru-core/mamoru-sniffer-c"}
mamoru-sniffer-c = {git = "https://github.com/Mamoru-Foundation/mamoru-core", rev = "bf805159f65611ce4d6137025c0ad826ace2ea68"}
