// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Wed, 16 Aug 2023 12:46:08 CEST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

#include <libmamoru_sniffer_go.h>
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

