// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Fri, 19 Jul 2024 11:48:55 WEST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

#include <libmamoru_sniffer_go.h>
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

