// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Wed, 24 Jul 2024 12:07:50 WEST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

#include <libmamoru_sniffer_go.h>
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

