// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Thu, 18 May 2023 15:37:47 CEST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package generated_bindings
