// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Mon, 29 Jan 2024 13:52:58 WET.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package generated_bindings
