// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Tue, 29 Aug 2023 16:26:37 CEST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package generated_bindings

/*
#cgo CFLAGS: -I${SRCDIR}/../packaged/include
#cgo LDFLAGS: -lmamoru_sniffer_go
#cgo darwin,arm64 LDFLAGS: -framework Security -L${SRCDIR}/../packaged/lib/darwin-arm64
#cgo linux,amd64 LDFLAGS: -Wl,--no-as-needed -ldl -lm -L${SRCDIR}/../packaged/lib/linux-amd64
#include <libmamoru_sniffer_go.h>
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"

// FfiSnifferResultT as declared in include/libmamoru_sniffer_go.h:17
type FfiSnifferResultT C.FfiSnifferResult_t

// FfiSnifferT as declared in include/libmamoru_sniffer_go.h:27
type FfiSnifferT C.FfiSniffer_t

// FfiValueT as declared in include/libmamoru_sniffer_go.h:36
type FfiValueT C.FfiValue_t

// FfiValueDataT as declared in include/libmamoru_sniffer_go.h:38
type FfiValueDataT C.FfiValueData_t

// FfiEvmBlockchainDataBuilderT as declared in include/libmamoru_sniffer_go.h:81
type FfiEvmBlockchainDataBuilderT C.FfiEvmBlockchainDataBuilder_t

// FfiEvmBlockchainDataCtxT as declared in include/libmamoru_sniffer_go.h:105
type FfiEvmBlockchainDataCtxT C.FfiEvmBlockchainDataCtx_t

// SliceRefUint8T as declared in include/libmamoru_sniffer_go.h:145
type SliceRefUint8T struct {
	Ptr            *byte
	Len            uint64
	refd8594c66    *C.slice_ref_uint8_t
	allocsd8594c66 interface{}
}
