// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Wed, 08 Mar 2023 12:10:11 CET.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package generated_bindings

/*
#cgo CFLAGS: -I${SRCDIR}/../packaged/include
#cgo LDFLAGS: -lmamoru_sniffer_go
#cgo darwin,arm64 LDFLAGS: -framework Security -L${SRCDIR}/../packaged/lib/darwin-arm64
#cgo linux,amd64 LDFLAGS: -Wl,--no-as-needed -ldl -lm -L${SRCDIR}/../packaged/lib/linux-amd64
#include <libmamoru_sniffer_go.h>
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"

// FfiTransactionBatchT as declared in include/libmamoru_sniffer_go.h:17
type FfiTransactionBatchT C.FfiTransactionBatch_t

// SliceRefUint8T as declared in include/libmamoru_sniffer_go.h:50
type SliceRefUint8T struct {
	Ptr            *byte
	Len            uint64
	refd8594c66    *C.slice_ref_uint8_t
	allocsd8594c66 interface{}
}

// FfiBlockchainDataT as declared in include/libmamoru_sniffer_go.h:70
type FfiBlockchainDataT C.FfiBlockchainData_t

// FfiCallTraceBatchT as declared in include/libmamoru_sniffer_go.h:78
type FfiCallTraceBatchT C.FfiCallTraceBatch_t

// FfiBlockBatchT as declared in include/libmamoru_sniffer_go.h:102
type FfiBlockBatchT C.FfiBlockBatch_t

// FfiEventBatchT as declared in include/libmamoru_sniffer_go.h:128
type FfiEventBatchT C.FfiEventBatch_t

// FfiSnifferResultT as declared in include/libmamoru_sniffer_go.h:153
type FfiSnifferResultT C.FfiSnifferResult_t

// FfiSnifferT as declared in include/libmamoru_sniffer_go.h:163
type FfiSnifferT C.FfiSniffer_t

// FfiBlockchainDataCtxT as declared in include/libmamoru_sniffer_go.h:172
type FfiBlockchainDataCtxT C.FfiBlockchainDataCtx_t

// FfiBlockchainDataCtxBuilderT as declared in include/libmamoru_sniffer_go.h:181
type FfiBlockchainDataCtxBuilderT C.FfiBlockchainDataCtxBuilder_t

// FfiValueT as declared in include/libmamoru_sniffer_go.h:201
type FfiValueT C.FfiValue_t

// FfiValueDataT as declared in include/libmamoru_sniffer_go.h:203
type FfiValueDataT C.FfiValueData_t
